### ISSUE TITLE
I can not find shortcut on spotlight and shortcuts app

### ISSUE THREAD

**Issue by Fihade** [mralexhay/Booky#2]

**Comment by mralexhay** [comment]
Take a look at the 'requirement' section of the readme - have you modified xcode-select to point to the Xcode beta? It's a known issue on dev beta 1.

After doing that, you may need to clear dervived data/clean build/restart if it's still not showing.

**Comment by boxabirds** [comment]
I concur xcode => Product => Clean Build Folder needed to be run after changing `xcode-select` otherwise Booky would not appear in the Shortcuts app.

**Comment by sonasapps** [comment]
Hmm, I still can't get it to work on Beta 4. I've ran `xcode-select`, cleaned build, restarted laptop and test device, still no dice.

**Comment by sonasapps** [comment]
Turns out the shortcuts are there, but you have to add them manually in the shortcuts app, which is not expected based on the WWDC presentation.
