### ISSUE TITLE
 'AddBook' does not conform to protocol 'AppIntent'

### ISSUE THREAD

**Issue by Rambo55555** [mralexhay/Booky#4]
<img width="254" alt="image" src="https://user-images.githubusercontent.com/35163438/182142489-289be530-5163-4e85-ab1d-16eff27d1bcf.png">
I build the project but failed...

**Comment by Rambo55555** [comment]
I have solved this problem, but I don't know why. I deleted the template ``<ShortcutsBookEntity>``
<img width="1607" alt="image" src="https://user-images.githubusercontent.com/35163438/182144880-2aadecec-afe1-4e6a-ab41-34ec3bb64d93.png">
<img width="1588" alt="image" src="https://user-images.githubusercontent.com/35163438/182144914-22e51277-bb7e-4d41-bebd-6450c16d4241.png">
So what is the problem🤔

**Comment by mralexhay** [comment]
There have been some breaking changes in beta 4, I'll try and update the project later today
